-- SQL Script to Populate/Update Unique Sitewide Meta Descriptions & Titles in 'seos' table for https://www.onlinetxttools.com

INSERT INTO `seos` (`url`, `title`, `description`, `keywords`, `og_title`, `og_description`, `og_image`, `canonical`, `created_at`, `updated_at`)
VALUES
('/', 
 'Free Online Text Tools – Case Converter, Word Counter & More', 
 'Free online text processing tools for developers, writers, and content creators. Convert case, count words, generate secure passwords, and format text instantly.', 
 'online text tools, text tools, free text utilities, case converter, word counter, password generator', 
 'Free Online Text Tools – Fast & Secure Browser Utilities', 
 'Free online text processing tools for developers, writers, and content creators. Instant browser-based text utilities.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/', NOW(), NOW()),

('/tools', 
 'All Free Online Text Processing Tools | ToolIt', 
 'Browse our complete suite of free online text processing tools. Fast, secure, browser-based utilities for text formatting, case conversion, and word counting.', 
 'text tools directory, free online text utilities, developer tools, writing tools, text formatting', 
 'All Free Online Text Tools – Full Suite', 
 'Browse our complete directory of free online text tools including case converters, word counters, and password generators.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/tools', NOW(), NOW()),

('/tools/case-converter', 
 'Free Online Case Converter – Uppercase, Lowercase, Title Case', 
 'Convert text case instantly online. Convert to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case for free.', 
 'case converter, uppercase converter, lowercase converter, title case, camelcase converter, convert text case', 
 'Free Online Case Converter Tool', 
 'Convert text case instantly: UPPERCASE, lowercase, Title Case, camelCase, PascalCase, snake_case, and kebab-case.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/tools/case-converter', NOW(), NOW()),

('/tools/word-counter', 
 'Free Word Counter & Character Counter Tool', 
 'Count words, characters, sentences, and paragraphs in real time. Perfect for essay writing, social media posts, blog editing, and SEO word limits.', 
 'word counter, character counter, count words online, sentence counter, paragraph counter, text length checker', 
 'Free Online Word & Character Counter', 
 'Count words, characters, sentences, and paragraphs in real time. Free client-side word count tool.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/tools/word-counter', NOW(), NOW()),

('/tools/password-generator', 
 'Free Strong Password Generator – Secure & Customizable', 
 'Generate strong, random, and secure passwords instantly in your browser. Customize password length, symbols, numbers, and uppercase characters with zero server storage.', 
 'password generator, secure password generator, random password generator, strong password tool, online password creator', 
 'Free Strong & Secure Password Generator', 
 'Generate custom random secure passwords instantly inside your browser. 100% private & secure.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/tools/password-generator', NOW(), NOW()),

('/tools/text-reverser', 
 'Free Online Text Reverser – Reverse Words & Letters', 
 'Reverse text, flip words, and invert character order instantly online. Simple, fast, and free client-side text reversing tool.', 
 'text reverser, reverse text online, flip text, backwards text generator, reverse string tool', 
 'Free Online Text Reverser', 
 'Reverse text strings, words, and letters instantly online.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/tools/text-reverser', NOW(), NOW()),

('/tools/whitespace-remover', 
 'Free Whitespace Remover & Line Trim Tool', 
 'Remove extra spaces, tabs, line breaks, and whitespace from text or code. Clean up formatted text quickly and easily.', 
 'whitespace remover, remove extra spaces, trim text, remove line breaks, text cleaner, space remover', 
 'Free Whitespace & Extra Space Remover', 
 'Clean up extra spaces, line breaks, and tabs from your text or code instantly.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/tools/whitespace-remover', NOW(), NOW()),

('/about', 
 'About Online Text Tools – Our Mission & Features', 
 'Learn about Online Text Tools. We provide fast, privacy-focused, browser-based text processing tools with zero registration required.', 
 'about online text tools, free text utilities mission, privacy text tools', 
 'About Online Text Tools', 
 'Learn more about our mission to provide fast, free, and privacy-first text tools.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/about', NOW(), NOW()),

('/contact', 
 'Contact Us – Online Text Tools Support & Feedback', 
 'Get in touch with the Online Text Tools team for feature requests, bug reports, or general inquiries. We reply within 24 hours.', 
 'contact online text tools, text tools support, feedback', 
 'Contact Online Text Tools Support', 
 'Have questions or feedback? Contact the Online Text Tools team directly.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/contact', NOW(), NOW()),

('/privacy-policy', 
 'Privacy Policy – Online Text Tools', 
 'Read our Privacy Policy. All text processing happens 100% locally in your browser. No user text or data is collected or saved on servers.', 
 'privacy policy, text tools privacy, data security', 
 'Privacy Policy – Online Text Tools', 
 'Read our commitment to user privacy and 100% browser-side data security.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/privacy-policy', NOW(), NOW()),

('/terms-of-use', 
 'Terms of Use – Online Text Tools', 
 'Terms of Use for Online Text Tools. Learn about the terms, conditions, and acceptable usage guidelines for our free web utilities.', 
 'terms of use, terms of service, text tools terms', 
 'Terms of Use – Online Text Tools', 
 'Review the terms and acceptable usage guidelines for Online Text Tools.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/terms-of-use', NOW(), NOW()),

('/ads-disclosure', 
 'Advertising & Ads Disclosure – Online Text Tools', 
 'Understand how advertising helps keep Online Text Tools 100% free for everyone. Learn about our ad policy and third-party partner disclosures.', 
 'ads disclosure, advertising policy, free tools funding', 
 'Ads Disclosure – Online Text Tools', 
 'Learn how advertising supports keeping our text tools completely free.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/ads-disclosure', NOW(), NOW()),

('/header-and-footer-script-adder', 
 'Header & Footer Script Adder Plugin – Custom Script Tool', 
 'Easily add custom scripts, Google Analytics, tracking pixels, and CSS tags to your site head and footer without editing template files.', 
 'header footer script adder, add custom scripts, google analytics code adder, web script plugin', 
 'Header & Footer Script Adder Plugin', 
 'Easily manage header and footer scripts, analytics, and custom code tags.', 
 'default-og-image.png', 
 'https://www.onlinetxttools.com/header-and-footer-script-adder', NOW(), NOW())

ON DUPLICATE KEY UPDATE 
  `title` = VALUES(`title`),
  `description` = VALUES(`description`),
  `keywords` = VALUES(`keywords`),
  `og_title` = VALUES(`og_title`),
  `og_description` = VALUES(`og_description`),
  `og_image` = VALUES(`og_image`),
  `canonical` = VALUES(`canonical`),
  `updated_at` = NOW();
