@extends('layouts.app')

@section('title', 'Terms of Use')

@section('content')
<div class="container py-5">
    <h1 class="mb-4">Terms of Use</h1>
    <p>Last updated: {{ date('F j, Y') }}</p>

    <p>Welcome to <strong>{{ config('app.name') }}</strong>! By using our website, you agree to the following terms and conditions. Please read them carefully.</p>

    <h3>Use of Our Tools</h3>
    <p>Our tools are provided for personal and educational use only. You agree not to misuse or attempt to harm, disrupt, or exploit the website or its tools.</p>

    <h3>Accuracy of Information</h3>
    <p>We strive to ensure that all information and results generated by our tools are accurate. However, we make no guarantees and are not liable for errors or losses arising from their use.</p>

    <h3>Intellectual Property</h3>
    <p>All content, code, and design elements on this website are the property of <strong>{{ config('app.name') }}</strong> unless otherwise stated. You may not reproduce or redistribute them without permission.</p>

    <h3>Third-Party Links</h3>
    <p>Some pages may contain links to third-party websites. We are not responsible for the content or practices of these sites.</p>

    <h3>Limitation of Liability</h3>
    <p>We are not responsible for any damages resulting from your use of our site or tools.</p>

    <h3>Changes to Terms</h3>
    <p>We may modify these terms at any time. Continued use of the site after updates constitutes acceptance of the revised terms.</p>
</div>
@endsection
