@extends('layouts.app')

@section('title', 'Terms of Use')

@section('content')
<div class="container py-5">
    <h1 class="mb-4">Terms of Use</h1>
    <p class="text-muted">Last updated: {{ date('F j, Y') }}</p>

    <p>Welcome to <strong>{{ config('app.name') }}</strong> (accessible from <a href="{{ url('/') }}">{{ request()->getHost() }}</a>). By accessing or using our website and online text utility tools, you agree to comply with and be bound by the following terms and conditions of use. Please read them carefully. If you do not agree to these terms, you must not use our website or services.</p>

    <h2 class="h4 mt-4 mb-3">1. Acceptance of Terms</h2>
    <p>By accessing, browsing, or using this website, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use, as well as our Privacy Policy. These terms apply to all visitors, users, and others who access or use the website.</p>

    <h2 class="h4 mt-4 mb-3">2. Use of Our Tools and Services</h2>
    <p>We provide a variety of online utility tools (including Case Converter, Word Counter, Password Generator, Text Reverser, and Whitespace Remover) designed for personal, educational, and professional use. In using these tools, you agree that:</p>
    <ul>
        <li>You will not use the website or tools for any unlawful purpose or in any way that violates applicable local, national, or international laws.</li>
        <li>You will not attempt to disrupt, compromise, or interfere with the security, integrity, or performance of the website, its hosting servers, or network systems.</li>
        <li>You will not upload or transmit viruses, malware, or any other type of malicious code that could affect the functionality or operation of the website.</li>
        <li>You will not use automated scripts, bots, scrapers, or other software to extract data or interact with our tools excessively without prior written consent.</li>
    </ul>

    <h2 class="h4 mt-4 mb-3">3. User Content and Privacy</h2>
    <p>Many of our tools process text that you type or paste into input fields. We respect your data privacy. As detailed in our Privacy Policy, all processing is performed locally within your web browser (client-side). We do not store, monitor, or transmit your input text to our servers. However, you are solely responsible for any content you input or process using our tools, ensuring you have the legal right to use and format such content.</p>

    <h2 class="h4 mt-4 mb-3">4. Intellectual Property Rights</h2>
    <p>All original content, features, functionality, source code, designs, graphics, and layout on this website are the exclusive property of <strong>{{ config('app.name') }}</strong> and its licensors, and are protected by copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, modify, create derivative works of, publicly display, or commercially exploit any part of our website without explicit written permission from us.</p>

    <h2 class="h4 mt-4 mb-3">5. Disclaimer of Warranties</h2>
    <p>Our website, tools, and content are provided on an "as is" and "as available" basis, without any warranties of any kind, either express or implied. We do not guarantee that:</p>
    <ul>
        <li>The website or tools will be uninterrupted, secure, or free from errors, bugs, or viruses.</li>
        <li>The results generated by the tools will be 100% accurate, reliable, or suited to your specific needs.</li>
        <li>Any errors in the website or tools will be corrected immediately.</li>
    </ul>
    <p>Your use of the website and tools is entirely at your own risk. We disclaim all warranties, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>

    <h2 class="h4 mt-4 mb-3">6. Limitation of Liability</h2>
    <p>To the maximum extent permitted by applicable law, in no event shall <strong>{{ config('app.name') }}</strong>, its developers, owners, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including without limitation loss of profits, data, use, goodwill, or other intangible losses, arising out of or in connection with:</p>
    <ul>
        <li>Your access to, use of, or inability to access or use the website or tools.</li>
        <li>Any errors, omissions, or inaccuracies in the results generated by the tools.</li>
        <li>Any unauthorized access to or alteration of your transmissions or data.</li>
    </ul>

    <h2 class="h4 mt-4 mb-3">7. Third-Party Links</h2>
    <p>Our website may contain links to third-party websites, advertisers, or services that are not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites. You acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with your use of any such content, goods, or services available on or through any such websites.</p>

    <h2 class="h4 mt-4 mb-3">8. Changes to These Terms</h2>
    <p>We reserve the right, at our sole discretion, to modify or replace these Terms of Use at any time. Any changes will be posted on this page with an updated "Last updated" date. Your continued use of the website and tools after any modifications constitute acceptance of the new terms. We encourage you to review this page periodically to stay informed of any updates.</p>

    <h2 class="h4 mt-4 mb-3">9. Contact Us</h2>
    <p>If you have any questions or concerns about these Terms of Use, please contact us at <a href="mailto:support@{{ request()->getHost() }}">support@{{ request()->getHost() }}</a> or visit our <a href="{{ route('contact') }}">Contact Page</a>.</p>
</div>
@endsection
